# Load in in NumPy

In [1]:
# import lib
import numpy as np

#### The basics

In [2]:
# Array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get dimention
a.ndim
# b.ndim

1

In [5]:
# Get shape
# a.shape
b.shape

(2, 3)

In [6]:
# Get type
a.dtype

dtype('int64')

In [7]:
# Get size
a.itemsize

8

In [8]:
# Get total size
# a.size
a.nbytes

24

## Accessing/Changing specifc elements, rows, and columns

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get specific element
a[1,5]

13

In [11]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [13]:
# Gettting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [14]:
# changing the value of a specific element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### 3-d example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get a specific element (work outside in)
b[0,1,1]

4

#### Initializing Different Types of Arrays

In [18]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Any other number
np.full((3,2),99)

array([[99, 99],
       [99, 99],
       [99, 99]])

In [21]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.33386047, 0.12550975, 0.01100201],
        [0.73997939, 0.38929641, 0.34964865]],

       [[0.2689124 , 0.76702578, 0.46456687],
        [0.73978139, 0.76436407, 0.95817489]],

       [[0.23740006, 0.58749462, 0.73477799],
        [0.1087525 , 0.41399839, 0.7459854 ]],

       [[0.69601486, 0.47064429, 0.40008221],
        [0.20301467, 0.50919238, 0.83993651]]])

In [23]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.61013396, 0.24846234, 0.56948088, 0.35065466, 0.78107122,
        0.8888694 , 0.85986197],
       [0.75533906, 0.06773379, 0.74050803, 0.02573948, 0.85368732,
        0.65594685, 0.02323298]])

In [24]:
# Random integer numbers
np.random.randint(7, size=(3,3))

array([[6, 1, 5],
       [3, 6, 1],
       [1, 5, 1]])

In [25]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Problem #1 - Simple exercise

In [27]:
output = np.ones((5,5))
print(output)

inner = np.zeros((3,3))
inner[1,1] = 9
print(inner)
output[1:4,1:4] = inner
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [28]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)


[100   2   3]


#### Mathematics

In [29]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [30]:
a + 2

array([3, 4, 5, 6])

In [31]:
a - 2

array([-1,  0,  1,  2])

In [32]:
a * 2

array([2, 4, 6, 8])

In [33]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [34]:
b = np.array([1,2,3,4])

a + b

array([2, 4, 6, 8])

In [35]:
a ** 2

array([ 1,  4,  9, 16])

#### Linear Algebra

In [36]:
a = np.ones((2,3))
print(a)


b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [37]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [39]:
# find the determinant 
c = np.identity(3)
np.linalg.det(c)

1.0

#### https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

#### Statistics

In [40]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.min(stats, axis=1)

array([1, 4])

In [43]:
np.max(stats, axis=1)

array([3, 6])

In [47]:
np.sum(stats, axis=0)

array([5, 7, 9])