# Load in in NumPy

In [2]:
# import lib
import numpy as np

#### The basics

In [4]:
# Array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get dimention
a.ndim
# b.ndim

1

In [10]:
# Get shape
# a.shape
b.shape

(2, 3)

In [11]:
# Get type
a.dtype

dtype('int64')

In [13]:
# Get size
a.itemsize

8

In [16]:
# Get total size
# a.size
a.nbytes

24