# Load in in NumPy

In [1]:
# import lib
import numpy as np

#### The basics

In [2]:
# Array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get dimention
a.ndim
# b.ndim

1

In [5]:
# Get shape
# a.shape
b.shape

(2, 3)

In [6]:
# Get type
a.dtype

dtype('int64')

In [7]:
# Get size
a.itemsize

8

In [8]:
# Get total size
# a.size
a.nbytes

24

## Accessing/Changing specifc elements, rows, and columns

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get specific element
a[1,5]

13

In [11]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [13]:
# Gettting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [14]:
# changing the value of a specific element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### 3-d example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get a specific element (work outside in)
b[0,1,1]

4

#### Initializing Different Types of Arrays

In [18]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Any other number
np.full((3,2),99)

array([[99, 99],
       [99, 99],
       [99, 99]])

In [21]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.57164756, 0.02525258, 0.45203145],
        [0.66621585, 0.82571918, 0.09278586]],

       [[0.43440154, 0.29396997, 0.09912946],
        [0.75849374, 0.22006147, 0.73040799]],

       [[0.39686842, 0.19537857, 0.03235392],
        [0.8501136 , 0.42850445, 0.16969979]],

       [[0.75080626, 0.51243359, 0.03794676],
        [0.51922677, 0.28679895, 0.63507802]]])

In [23]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.35164815, 0.16134686, 0.62229283, 0.48470518, 0.38196314,
        0.87118724, 0.62944719],
       [0.01670521, 0.18734708, 0.05360101, 0.33988137, 0.70325235,
        0.92141339, 0.25523088]])

In [24]:
# Random integer numbers
np.random.randint(7, size=(3,3))

array([[5, 3, 0],
       [1, 3, 5],
       [5, 3, 0]])

In [25]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Problem #1 - Simple exercise

In [39]:
output = np.ones((5,5))
print(output)

inner = np.zeros((3,3))
inner[1,1] = 9
print(inner)
output[1:4,1:4] = inner
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [41]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)


[100   2   3]


#### Mathematics

In [42]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [43]:
a + 2

array([3, 4, 5, 6])

In [44]:
a - 2

array([-1,  0,  1,  2])

In [45]:
a * 2

array([2, 4, 6, 8])

In [46]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [47]:
b = np.array([1,2,3,4])

a + b

array([2, 4, 6, 8])

In [48]:
a ** 2

array([ 1,  4,  9, 16])