# Load in in NumPy

In [3]:
# import lib
import numpy as np

#### The basics

In [4]:
# Array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get dimention
a.ndim
# b.ndim

1

In [7]:
# Get shape
# a.shape
b.shape

(2, 3)

In [8]:
# Get type
a.dtype

dtype('int64')

In [9]:
# Get size
a.itemsize

8

In [10]:
# Get total size
# a.size
a.nbytes

24

## Accessing/Changing specifc elements, rows, and columns

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# Get specific element
a[1,5]

13

In [14]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [17]:
# Gettting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [18]:
# changing the value of a specific element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [20]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### 3-d example

In [22]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
# Get a specific element (work outside in)
b[0,1,1]

4