# Load in in NumPy

In [1]:
# import lib
import numpy as np

#### The basics

In [2]:
# Array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get dimention
a.ndim
# b.ndim

1

In [5]:
# Get shape
# a.shape
b.shape

(2, 3)

In [6]:
# Get type
a.dtype

dtype('int64')

In [7]:
# Get size
a.itemsize

8

In [8]:
# Get total size
# a.size
a.nbytes

24

## Accessing/Changing specifc elements, rows, and columns

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get specific element
a[1,5]

13

In [11]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [13]:
# Gettting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [14]:
# changing the value of a specific element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### 3-d example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get a specific element (work outside in)
b[0,1,1]

4

#### Initializing Different Types of Arrays

In [19]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# Any other number
np.full((3,2),99)

array([[99, 99],
       [99, 99],
       [99, 99]])

In [24]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.95928355, 0.73596234, 0.53790886],
        [0.55405473, 0.68251706, 0.63926667]],

       [[0.53277419, 0.00476516, 0.12109853],
        [0.9955202 , 0.56051359, 0.57292021]],

       [[0.56321691, 0.77285949, 0.62612903],
        [0.02701079, 0.4210731 , 0.88176398]],

       [[0.7586003 , 0.61512915, 0.90381243],
        [0.97154243, 0.9140912 , 0.4289249 ]]])

In [27]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.22312721, 0.4801742 , 0.45051468, 0.69716466, 0.36363366,
        0.39605067, 0.3809956 ],
       [0.02517478, 0.78107252, 0.51068122, 0.55587362, 0.45469877,
        0.52318954, 0.50706094]])

In [29]:
# Random integer numbers
np.random.randint(7, size=(3,3))

array([[6, 3, 1],
       [4, 0, 0],
       [2, 6, 4]])

In [33]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
